// WARNING: This file has automatically been generated on Wed, 29 Mar 2023 14:35:46 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package cipvs

const (
	// _H as defined in cipvs/ip_vs.h:8

	// VersionCode as defined in cipvs/ip_vs.h:12
	VersionCode = 0x010201
	// SvcFPersistent as defined in cipvs/ip_vs.h:21
	SvcFPersistent = 0x0001
	// SvcFHashed as defined in cipvs/ip_vs.h:22
	SvcFHashed = 0x0002
	// SvcFOnepacket as defined in cipvs/ip_vs.h:23
	SvcFOnepacket = 0x0004
	// SvcFSched1 as defined in cipvs/ip_vs.h:24
	SvcFSched1 = 0x0008
	// SvcFSched2 as defined in cipvs/ip_vs.h:25
	SvcFSched2 = 0x0010
	// SvcFSched3 as defined in cipvs/ip_vs.h:26
	SvcFSched3 = 0x0020
	// SvcFSchedShFallback as defined in cipvs/ip_vs.h:28
	SvcFSchedShFallback = SvcFSched1
	// SvcFSchedShPort as defined in cipvs/ip_vs.h:29
	SvcFSchedShPort = SvcFSched2
	// DestFAvailable as defined in cipvs/ip_vs.h:34
	DestFAvailable = 0x0001
	// DestFOverload as defined in cipvs/ip_vs.h:35
	DestFOverload = 0x0002
	// StateNone as defined in cipvs/ip_vs.h:40
	StateNone = 0x0000
	// StateMaster as defined in cipvs/ip_vs.h:41
	StateMaster = 0x0001
	// StateBackup as defined in cipvs/ip_vs.h:42
	StateBackup = 0x0002
	// ConnFFwdMask as defined in cipvs/ip_vs.h:82
	ConnFFwdMask = 0x0007
	// ConnFMasq as defined in cipvs/ip_vs.h:83
	ConnFMasq = 0x0000
	// ConnFLocalnode as defined in cipvs/ip_vs.h:84
	ConnFLocalnode = 0x0001
	// ConnFTunnel as defined in cipvs/ip_vs.h:85
	ConnFTunnel = 0x0002
	// ConnFDroute as defined in cipvs/ip_vs.h:86
	ConnFDroute = 0x0003
	// ConnFBypass as defined in cipvs/ip_vs.h:87
	ConnFBypass = 0x0004
	// ConnFSync as defined in cipvs/ip_vs.h:88
	ConnFSync = 0x0020
	// ConnFHashed as defined in cipvs/ip_vs.h:89
	ConnFHashed = 0x0040
	// ConnFNooutput as defined in cipvs/ip_vs.h:90
	ConnFNooutput = 0x0080
	// ConnFInactive as defined in cipvs/ip_vs.h:91
	ConnFInactive = 0x0100
	// ConnFOutSeq as defined in cipvs/ip_vs.h:92
	ConnFOutSeq = 0x0200
	// ConnFInSeq as defined in cipvs/ip_vs.h:93
	ConnFInSeq = 0x0400
	// ConnFSeqMask as defined in cipvs/ip_vs.h:94
	ConnFSeqMask = 0x0600
	// ConnFNoCport as defined in cipvs/ip_vs.h:95
	ConnFNoCport = 0x0800
	// ConnFTemplate as defined in cipvs/ip_vs.h:96
	ConnFTemplate = 0x1000
	// ConnFOnePacket as defined in cipvs/ip_vs.h:97
	ConnFOnePacket = 0x2000
	// ConnFBackupMask as defined in cipvs/ip_vs.h:100
	ConnFBackupMask = (ConnFFwdMask | ConnFNooutput | ConnFInactive | ConnFSeqMask | ConnFNoCport | ConnFTemplate)
	// ConnFBackupUpdMask as defined in cipvs/ip_vs.h:109
	ConnFBackupUpdMask = (ConnFInactive | ConnFSeqMask)
	// ConnFNfct as defined in cipvs/ip_vs.h:113
	ConnFNfct = (1 << 16)
	// ConnFDestMask as defined in cipvs/ip_vs.h:116
	ConnFDestMask = (ConnFFwdMask | ConnFOnePacket | ConnFNfct | 0)
	// SchednameMaxlen as defined in cipvs/ip_vs.h:121
	SchednameMaxlen = 16
	// PenameMaxlen as defined in cipvs/ip_vs.h:122
	PenameMaxlen = 16
	// IfnameMaxlen as defined in cipvs/ip_vs.h:123
	IfnameMaxlen = 16
	// PedataMaxlen as defined in cipvs/ip_vs.h:125
	PedataMaxlen = 255
	// TunnelEncapFlagNocsum as defined in cipvs/ip_vs.h:136
	TunnelEncapFlagNocsum = (0)
	// TunnelEncapFlagCsum as defined in cipvs/ip_vs.h:137
	TunnelEncapFlagCsum = (1 << 0)
	// TunnelEncapFlagRemcsum as defined in cipvs/ip_vs.h:138
	TunnelEncapFlagRemcsum = (1 << 1)
	// GenlName as defined in cipvs/ip_vs.h:299
	GenlName = "IPVS"
	// GenlVersion as defined in cipvs/ip_vs.h:300
	GenlVersion = 0x1
	// CmdMax as defined in cipvs/ip_vs.h:337
	CmdMax = (__CmdMax - 1)
	// CmdAttrMax as defined in cipvs/ip_vs.h:351
	CmdAttrMax = (__CmdAttrMax - 1)
	// SvcAttrMax as defined in cipvs/ip_vs.h:380
	SvcAttrMax = (__SvcAttrMax - 1)
	// DestAttrMax as defined in cipvs/ip_vs.h:417
	DestAttrMax = (__DestAttrMax - 1)
	// DaemonAttrMax as defined in cipvs/ip_vs.h:437
	DaemonAttrMax = (__DaemonAttrMax - 1)
	// StatsAttrMax as defined in cipvs/ip_vs.h:462
	StatsAttrMax = (__StatsAttrMax - 1)
	// InfoAttrMax as defined in cipvs/ip_vs.h:472
	InfoAttrMax = (__InfoAttrMax - 1)
)

const (
	// ConnFTunnelTypeIpip as declared in cipvs/ip_vs.h:129
	ConnFTunnelTypeIpip = iota
	// ConnFTunnelTypeGue as declared in cipvs/ip_vs.h:130
	ConnFTunnelTypeGue = 1
	// ConnFTunnelTypeGre as declared in cipvs/ip_vs.h:131
	ConnFTunnelTypeGre = 2
	// ConnFTunnelTypeMax as declared in cipvs/ip_vs.h:132
	ConnFTunnelTypeMax = 3
)

const (
	// CmdUnspec as declared in cipvs/ip_vs.h:309
	CmdUnspec = iota
	// CmdNewService as declared in cipvs/ip_vs.h:311
	CmdNewService = 1
	// CmdSetService as declared in cipvs/ip_vs.h:312
	CmdSetService = 2
	// CmdDelService as declared in cipvs/ip_vs.h:313
	CmdDelService = 3
	// CmdGetService as declared in cipvs/ip_vs.h:314
	CmdGetService = 4
	// CmdNewDest as declared in cipvs/ip_vs.h:316
	CmdNewDest = 5
	// CmdSetDest as declared in cipvs/ip_vs.h:317
	CmdSetDest = 6
	// CmdDelDest as declared in cipvs/ip_vs.h:318
	CmdDelDest = 7
	// CmdGetDest as declared in cipvs/ip_vs.h:319
	CmdGetDest = 8
	// CmdNewDaemon as declared in cipvs/ip_vs.h:321
	CmdNewDaemon = 9
	// CmdDelDaemon as declared in cipvs/ip_vs.h:322
	CmdDelDaemon = 10
	// CmdGetDaemon as declared in cipvs/ip_vs.h:323
	CmdGetDaemon = 11
	// CmdSetConfig as declared in cipvs/ip_vs.h:325
	CmdSetConfig = 12
	// CmdGetConfig as declared in cipvs/ip_vs.h:326
	CmdGetConfig = 13
	// CmdSetInfo as declared in cipvs/ip_vs.h:328
	CmdSetInfo = 14
	// CmdGetInfo as declared in cipvs/ip_vs.h:329
	CmdGetInfo = 15
	// CmdZero as declared in cipvs/ip_vs.h:331
	CmdZero = 16
	// CmdFlush as declared in cipvs/ip_vs.h:332
	CmdFlush = 17
	// __CmdMax as declared in cipvs/ip_vs.h:334
	__CmdMax = 18
)

const (
	// CmdAttrUnspec as declared in cipvs/ip_vs.h:341
	CmdAttrUnspec = iota
	// CmdAttrService as declared in cipvs/ip_vs.h:342
	CmdAttrService = 1
	// CmdAttrDest as declared in cipvs/ip_vs.h:343
	CmdAttrDest = 2
	// CmdAttrDaemon as declared in cipvs/ip_vs.h:344
	CmdAttrDaemon = 3
	// CmdAttrTimeoutTcp as declared in cipvs/ip_vs.h:345
	CmdAttrTimeoutTcp = 4
	// CmdAttrTimeoutTcpFin as declared in cipvs/ip_vs.h:346
	CmdAttrTimeoutTcpFin = 5
	// CmdAttrTimeoutUdp as declared in cipvs/ip_vs.h:347
	CmdAttrTimeoutUdp = 6
	// __CmdAttrMax as declared in cipvs/ip_vs.h:348
	__CmdAttrMax = 7
)

const (
	// SvcAttrUnspec as declared in cipvs/ip_vs.h:359
	SvcAttrUnspec = iota
	// SvcAttrAf as declared in cipvs/ip_vs.h:360
	SvcAttrAf = 1
	// SvcAttrProtocol as declared in cipvs/ip_vs.h:361
	SvcAttrProtocol = 2
	// SvcAttrAddr as declared in cipvs/ip_vs.h:362
	SvcAttrAddr = 3
	// SvcAttrPort as declared in cipvs/ip_vs.h:363
	SvcAttrPort = 4
	// SvcAttrFwmark as declared in cipvs/ip_vs.h:364
	SvcAttrFwmark = 5
	// SvcAttrSchedName as declared in cipvs/ip_vs.h:366
	SvcAttrSchedName = 6
	// SvcAttrFlags as declared in cipvs/ip_vs.h:367
	SvcAttrFlags = 7
	// SvcAttrTimeout as declared in cipvs/ip_vs.h:368
	SvcAttrTimeout = 8
	// SvcAttrNetmask as declared in cipvs/ip_vs.h:369
	SvcAttrNetmask = 9
	// SvcAttrStats as declared in cipvs/ip_vs.h:371
	SvcAttrStats = 10
	// SvcAttrPeName as declared in cipvs/ip_vs.h:373
	SvcAttrPeName = 11
	// SvcAttrStats64 as declared in cipvs/ip_vs.h:375
	SvcAttrStats64 = 12
	// __SvcAttrMax as declared in cipvs/ip_vs.h:377
	__SvcAttrMax = 13
)

const (
	// DestAttrUnspec as declared in cipvs/ip_vs.h:388
	DestAttrUnspec = iota
	// DestAttrAddr as declared in cipvs/ip_vs.h:389
	DestAttrAddr = 1
	// DestAttrPort as declared in cipvs/ip_vs.h:390
	DestAttrPort = 2
	// DestAttrFwdMethod as declared in cipvs/ip_vs.h:392
	DestAttrFwdMethod = 3
	// DestAttrWeight as declared in cipvs/ip_vs.h:393
	DestAttrWeight = 4
	// DestAttrUThresh as declared in cipvs/ip_vs.h:395
	DestAttrUThresh = 5
	// DestAttrLThresh as declared in cipvs/ip_vs.h:396
	DestAttrLThresh = 6
	// DestAttrActiveConns as declared in cipvs/ip_vs.h:398
	DestAttrActiveConns = 7
	// DestAttrInactConns as declared in cipvs/ip_vs.h:399
	DestAttrInactConns = 8
	// DestAttrPersistConns as declared in cipvs/ip_vs.h:400
	DestAttrPersistConns = 9
	// DestAttrStats as declared in cipvs/ip_vs.h:402
	DestAttrStats = 10
	// DestAttrAddrFamily as declared in cipvs/ip_vs.h:404
	DestAttrAddrFamily = 11
	// DestAttrStats64 as declared in cipvs/ip_vs.h:406
	DestAttrStats64 = 12
	// DestAttrTunType as declared in cipvs/ip_vs.h:408
	DestAttrTunType = 13
	// DestAttrTunPort as declared in cipvs/ip_vs.h:410
	DestAttrTunPort = 14
	// DestAttrTunFlags as declared in cipvs/ip_vs.h:412
	DestAttrTunFlags = 15
	// __DestAttrMax as declared in cipvs/ip_vs.h:414
	__DestAttrMax = 16
)

const (
	// DaemonAttrUnspec as declared in cipvs/ip_vs.h:425
	DaemonAttrUnspec = iota
	// DaemonAttrState as declared in cipvs/ip_vs.h:426
	DaemonAttrState = 1
	// DaemonAttrMcastIfn as declared in cipvs/ip_vs.h:427
	DaemonAttrMcastIfn = 2
	// DaemonAttrSyncId as declared in cipvs/ip_vs.h:428
	DaemonAttrSyncId = 3
	// DaemonAttrSyncMaxlen as declared in cipvs/ip_vs.h:429
	DaemonAttrSyncMaxlen = 4
	// DaemonAttrMcastGroup as declared in cipvs/ip_vs.h:430
	DaemonAttrMcastGroup = 5
	// DaemonAttrMcastGroup6 as declared in cipvs/ip_vs.h:431
	DaemonAttrMcastGroup6 = 6
	// DaemonAttrMcastPort as declared in cipvs/ip_vs.h:432
	DaemonAttrMcastPort = 7
	// DaemonAttrMcastTtl as declared in cipvs/ip_vs.h:433
	DaemonAttrMcastTtl = 8
	// __DaemonAttrMax as declared in cipvs/ip_vs.h:434
	__DaemonAttrMax = 9
)

const (
	// StatsAttrUnspec as declared in cipvs/ip_vs.h:446
	StatsAttrUnspec = iota
	// StatsAttrConns as declared in cipvs/ip_vs.h:447
	StatsAttrConns = 1
	// StatsAttrInpkts as declared in cipvs/ip_vs.h:448
	StatsAttrInpkts = 2
	// StatsAttrOutpkts as declared in cipvs/ip_vs.h:449
	StatsAttrOutpkts = 3
	// StatsAttrInbytes as declared in cipvs/ip_vs.h:450
	StatsAttrInbytes = 4
	// StatsAttrOutbytes as declared in cipvs/ip_vs.h:451
	StatsAttrOutbytes = 5
	// StatsAttrCps as declared in cipvs/ip_vs.h:453
	StatsAttrCps = 6
	// StatsAttrInpps as declared in cipvs/ip_vs.h:454
	StatsAttrInpps = 7
	// StatsAttrOutpps as declared in cipvs/ip_vs.h:455
	StatsAttrOutpps = 8
	// StatsAttrInbps as declared in cipvs/ip_vs.h:456
	StatsAttrInbps = 9
	// StatsAttrOutbps as declared in cipvs/ip_vs.h:457
	StatsAttrOutbps = 10
	// StatsAttrPad as declared in cipvs/ip_vs.h:458
	StatsAttrPad = 11
	// __StatsAttrMax as declared in cipvs/ip_vs.h:459
	__StatsAttrMax = 12
)

const (
	// InfoAttrUnspec as declared in cipvs/ip_vs.h:466
	InfoAttrUnspec = iota
	// InfoAttrVersion as declared in cipvs/ip_vs.h:467
	InfoAttrVersion = 1
	// InfoAttrConnTabSize as declared in cipvs/ip_vs.h:468
	InfoAttrConnTabSize = 2
	// __InfoAttrMax as declared in cipvs/ip_vs.h:469
	__InfoAttrMax = 3
)
